services:
  asics-bot:
    build: .
    container_name: asics-availability
    restart: unless-stopped
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - ./db:/app/db
    logging:
      options:
        max-size: "10m"
        max-file: "3"